services:
    frontend:
        image: yanshuy/express-app:latest
        ports:
            - 8080:8080
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
    watchtower:
        image: containrrr/watchtower
        environment:
            - WATCHTOWER_POLL_INTERVAL=30
            - WATCHTOWER_DEBUG=true
            - WATCHTOWER_CLEANUP=true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        container_name: watchtower
        labels:
            - "com.centurylinklabs.watchtower.enable=false"
        command: frontend
